name: Check source code

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: npm ci

      - name: Check formatting
        run: npm run check

      - name: Check linting
        run: npm run lint
